name: lojong_flutter_inspiracoes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.1
  #chucker_flutter: ^1.6.2
  card_swiper: ^3.0.1
  connectivity_plus: ^5.0.2
  dartz: ^0.10.1
  dio: ^5.4.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_file_store: ^1.2.3
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  flutter_svg: ^2.0.9
  flutter_svg_provider: ^1.0.7
  #google_fonts: ^6.1.0
  logging: ^1.2.0
  path_provider: ^2.1.2
  pod_player: ^0.2.1
  provider: ^6.1.1
  #vimeo_video_player: ^0.0.10
  #vimeo_player_flutter: ^0.1.0
  #youtube_player_flutter: ^8.1.2
  #youtube_player_iframe: ^4.0.4
  #youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
  fonts:
    - family: Asap
      fonts:
        - asset: fonts/Asap-Regular.ttf
